# Generated by Django 5.2.10 on 2026-03-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media/profile/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media/car/')),
                ('description', models.TextField(blank=True)),
                ('seats_available', models.PositiveSmallIntegerField(default=3)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
